[2025-09-16T18:49:43.421+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-09-16T18:49:43.469+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: train_model_dag_batch_iterative_85000.check_training_data manual__2025-09-16T18:49:36.382656+00:00 [queued]>
[2025-09-16T18:49:43.492+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: train_model_dag_batch_iterative_85000.check_training_data manual__2025-09-16T18:49:36.382656+00:00 [queued]>
[2025-09-16T18:49:43.494+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-09-16T18:49:43.534+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): check_training_data> on 2025-09-16 18:49:36.382656+00:00
[2025-09-16T18:49:43.571+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'train_model_dag_batch_iterative_85000', 'check_training_data', 'manual__2025-09-16T18:49:36.382656+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/train_dag.py', '--cfg-path', '/tmp/tmp0wh0nmab']
[2025-09-16T18:49:43.579+0000] {standard_task_runner.py:105} INFO - Job 12: Subtask check_training_data
[2025-09-16T18:49:43.596+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1380) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-16T18:49:43.598+0000] {standard_task_runner.py:72} INFO - Started process 1382 to run task
[2025-09-16T18:49:43.964+0000] {task_command.py:467} INFO - Running <TaskInstance: train_model_dag_batch_iterative_85000.check_training_data manual__2025-09-16T18:49:36.382656+00:00 [running]> on host 43cfe1078e43
[2025-09-16T18:49:44.363+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='train_model_dag_batch_iterative_85000' AIRFLOW_CTX_TASK_ID='check_training_data' AIRFLOW_CTX_EXECUTION_DATE='2025-09-16T18:49:36.382656+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-16T18:49:36.382656+00:00'
[2025-09-16T18:49:44.371+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-09-16T18:49:44.498+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-16T18:49:44.502+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "echo '=== Checking training data availability ===' && ls -lh /opt/airflow/data/ && [ -f /opt/airflow/data/X_train_update.csv ] || (echo 'Missing X_train_update.csv' && exit 1) && [ -f /opt/airflow/data/Y_train_CVw08PX.csv ] || (echo 'Missing Y_train_CVw08PX.csv' && exit 1) && [ -d /opt/airflow/data/images/image_train/ ] || (echo 'Missing training images' && exit 1) && echo 'âœ“ All training files are present'"]
[2025-09-16T18:49:44.527+0000] {subprocess.py:86} INFO - Output:
[2025-09-16T18:49:44.544+0000] {subprocess.py:93} INFO - === Checking training data availability ===
[2025-09-16T18:49:44.564+0000] {subprocess.py:93} INFO - total 0
[2025-09-16T18:49:44.565+0000] {subprocess.py:93} INFO - drwxr-xr-x 2 root root 40 Sep 16 17:16 artifacts
[2025-09-16T18:49:44.566+0000] {subprocess.py:93} INFO - drwxr-xr-x 2 root root 40 Sep 16 17:25 feature_cache
[2025-09-16T18:49:44.567+0000] {subprocess.py:93} INFO - drwxr-xr-x 2 root root 40 Sep 16 16:51 images
[2025-09-16T18:49:44.568+0000] {subprocess.py:93} INFO - Missing X_train_update.csv
[2025-09-16T18:49:44.569+0000] {subprocess.py:93} INFO - Missing Y_train_CVw08PX.csv
[2025-09-16T18:49:44.573+0000] {subprocess.py:93} INFO - Missing training images
[2025-09-16T18:49:44.576+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-09-16T18:49:44.596+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-09-16T18:49:44.620+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=train_model_dag_batch_iterative_85000, task_id=check_training_data, run_id=manual__2025-09-16T18:49:36.382656+00:00, execution_date=20250916T184936, start_date=20250916T184943, end_date=20250916T184944
[2025-09-16T18:49:44.702+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-09-16T18:49:44.703+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 12 for task check_training_data (Bash command failed. The command returned a non-zero exit code 1.; 1382)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-09-16T18:49:44.762+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-09-16T18:49:44.800+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py:1378 AirflowProviderDeprecationWarning: Call to deprecated class SimpleHttpOperator. (Class `SimpleHttpOperator` is deprecated and will be removed in a future release. Please use `HttpOperator` instead.)
[2025-09-16T18:49:44.907+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-16T18:49:44.914+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
