[2025-09-07T19:03:04.564+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-07T19:03:04.602+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: train_model_dag_batch_iterative_85000.train_model_iterative manual__2025-09-07T19:00:14.547126+00:00 [queued]>
[2025-09-07T19:03:04.617+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: train_model_dag_batch_iterative_85000.train_model_iterative manual__2025-09-07T19:00:14.547126+00:00 [queued]>
[2025-09-07T19:03:04.617+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-09-07T19:03:04.644+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): train_model_iterative> on 2025-09-07 19:00:14.547126+00:00
[2025-09-07T19:03:04.658+0000] {standard_task_runner.py:63} INFO - Started process 2118 to run task
[2025-09-07T19:03:04.662+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'train_model_dag_batch_iterative_85000', 'train_model_iterative', 'manual__2025-09-07T19:00:14.547126+00:00', '--job-id', '340', '--raw', '--subdir', 'DAGS_FOLDER/train_dag.py', '--cfg-path', '/tmp/tmp3y1kwslp']
[2025-09-07T19:03:04.665+0000] {standard_task_runner.py:91} INFO - Job 340: Subtask train_model_iterative
[2025-09-07T19:03:04.754+0000] {task_command.py:426} INFO - Running <TaskInstance: train_model_dag_batch_iterative_85000.train_model_iterative manual__2025-09-07T19:00:14.547126+00:00 [running]> on host 31d1c5cf642c
[2025-09-07T19:03:04.945+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='train_model_dag_batch_iterative_85000' AIRFLOW_CTX_TASK_ID='train_model_iterative' AIRFLOW_CTX_EXECUTION_DATE='2025-09-07T19:00:14.547126+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-07T19:00:14.547126+00:00'
[2025-09-07T19:03:04.950+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-07T19:03:10.814+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-07T19:03:10.815+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/train_dag.py", line 99, in send_batches_to_train_api
    raise Exception(f"Batch {idx} failed: {response.text}")
Exception: Batch 1 failed: Internal Server Error
[2025-09-07T19:03:10.830+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=train_model_dag_batch_iterative_85000, task_id=train_model_iterative, run_id=manual__2025-09-07T19:00:14.547126+00:00, execution_date=20250907T190014, start_date=20250907T190304, end_date=20250907T190310
[2025-09-07T19:03:10.848+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 340 for task train_model_iterative (Batch 1 failed: Internal Server Error; 2118)
[2025-09-07T19:03:10.897+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-09-07T19:03:10.925+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-07T19:03:10.932+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
