[2025-09-08T18:12:29.842+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-08T18:12:29.898+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: train_model_dag_batch_iterative_85000.train_model_iterative manual__2025-09-08T18:11:24.445369+00:00 [queued]>
[2025-09-08T18:12:29.926+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: train_model_dag_batch_iterative_85000.train_model_iterative manual__2025-09-08T18:11:24.445369+00:00 [queued]>
[2025-09-08T18:12:29.927+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-09-08T18:12:29.963+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): train_model_iterative> on 2025-09-08 18:11:24.445369+00:00
[2025-09-08T18:12:29.982+0000] {standard_task_runner.py:63} INFO - Started process 4798 to run task
[2025-09-08T18:12:29.989+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'train_model_dag_batch_iterative_85000', 'train_model_iterative', 'manual__2025-09-08T18:11:24.445369+00:00', '--job-id', '385', '--raw', '--subdir', 'DAGS_FOLDER/train_dag.py', '--cfg-path', '/tmp/tmpny0h0eeg']
[2025-09-08T18:12:29.998+0000] {standard_task_runner.py:91} INFO - Job 385: Subtask train_model_iterative
[2025-09-08T18:12:30.131+0000] {task_command.py:426} INFO - Running <TaskInstance: train_model_dag_batch_iterative_85000.train_model_iterative manual__2025-09-08T18:11:24.445369+00:00 [running]> on host 50a52b70bec0
[2025-09-08T18:12:30.532+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='train_model_dag_batch_iterative_85000' AIRFLOW_CTX_TASK_ID='train_model_iterative' AIRFLOW_CTX_EXECUTION_DATE='2025-09-08T18:11:24.445369+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-08T18:11:24.445369+00:00'
[2025-09-08T18:12:30.540+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-08T18:16:50.677+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-08T18:16:50.681+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/train_dag.py", line 99, in send_batches_to_train_api
    raise Exception(f"Batch {idx} failed: {response.text}")
Exception: Batch 1 failed: Internal Server Error
[2025-09-08T18:16:50.705+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=train_model_dag_batch_iterative_85000, task_id=train_model_iterative, run_id=manual__2025-09-08T18:11:24.445369+00:00, execution_date=20250908T181124, start_date=20250908T181229, end_date=20250908T181650
[2025-09-08T18:16:50.737+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 385 for task train_model_iterative (Batch 1 failed: Internal Server Error; 4798)
[2025-09-08T18:16:50.777+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-09-08T18:16:50.825+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-08T18:16:50.830+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
