[2025-09-07T09:15:38.387+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-07T09:15:38.414+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: train_model_dag.extract_features manual__2025-09-07T09:15:14.127486+00:00 [queued]>
[2025-09-07T09:15:38.428+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: train_model_dag.extract_features manual__2025-09-07T09:15:14.127486+00:00 [queued]>
[2025-09-07T09:15:38.429+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-09-07T09:15:38.453+0000] {taskinstance.py:2330} INFO - Executing <Task(SimpleHttpOperator): extract_features> on 2025-09-07 09:15:14.127486+00:00
[2025-09-07T09:15:38.464+0000] {standard_task_runner.py:63} INFO - Started process 1631 to run task
[2025-09-07T09:15:38.469+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'train_model_dag', 'extract_features', 'manual__2025-09-07T09:15:14.127486+00:00', '--job-id', '300', '--raw', '--subdir', 'DAGS_FOLDER/train_dag.py', '--cfg-path', '/tmp/tmpznfagqh2']
[2025-09-07T09:15:38.473+0000] {standard_task_runner.py:91} INFO - Job 300: Subtask extract_features
[2025-09-07T09:15:38.570+0000] {task_command.py:426} INFO - Running <TaskInstance: train_model_dag.extract_features manual__2025-09-07T09:15:14.127486+00:00 [running]> on host c35a2ba490cb
[2025-09-07T09:15:38.805+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='train_model_dag' AIRFLOW_CTX_TASK_ID='extract_features' AIRFLOW_CTX_EXECUTION_DATE='2025-09-07T09:15:14.127486+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-07T09:15:14.127486+00:00'
[2025-09-07T09:15:38.807+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-07T09:15:38.831+0000] {http.py:169} INFO - Calling HTTP method
[2025-09-07T09:15:38.834+0000] {base.py:84} INFO - Using connection ID 'preprocess_api' for task execution.
[2025-09-07T09:15:38.839+0000] {base.py:84} INFO - Using connection ID 'preprocess_api' for task execution.
[2025-09-07T10:59:33.260+0000] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to up_for_retry. Terminating instance.
[2025-09-07T10:59:33.264+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-09-07T10:59:33.270+0000] {process_utils.py:132} INFO - Sending 15 to group 1631. PIDs of all processes in the group: [1631]
[2025-09-07T10:59:33.270+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 1631
[2025-09-07T10:59:33.274+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-09-07T10:59:33.279+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-07T10:59:33.301+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 166, in execute
    return self.execute_sync(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 170, in execute_sync
    response = self.hook.run(self.endpoint, self.data, self.headers, self.extra_options)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/hooks/http.py", line 166, in run
    return self.run_and_check(session, prepped_request, extra_options)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/hooks/http.py", line 214, in run_and_check
    response = session.send(prepped_request, **send_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 462, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/usr/local/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.8/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2613, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2025-09-07T10:59:33.315+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=train_model_dag, task_id=extract_features, run_id=manual__2025-09-07T09:15:14.127486+00:00, execution_date=20250907T091514, start_date=20250907T091538, end_date=20250907T105933
[2025-09-07T10:59:33.365+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=1631, status='terminated', exitcode=2, started='09:15:38') (1631) terminated with exit code 2
