[2025-09-17T18:45:08.000+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-09-17T18:45:08.048+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: rakuten_multimodal_pipeline.check_training_data manual__2025-09-17T18:45:06.127533+00:00 [queued]>
[2025-09-17T18:45:08.068+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: rakuten_multimodal_pipeline.check_training_data manual__2025-09-17T18:45:06.127533+00:00 [queued]>
[2025-09-17T18:45:08.069+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-09-17T18:45:08.101+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): check_training_data> on 2025-09-17 18:45:06.127533+00:00
[2025-09-17T18:45:08.110+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'rakuten_multimodal_pipeline', 'check_training_data', 'manual__2025-09-17T18:45:06.127533+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/train_dag_40.py', '--cfg-path', '/tmp/tmphoqd7rkb']
[2025-09-17T18:45:08.113+0000] {standard_task_runner.py:105} INFO - Job 6: Subtask check_training_data
[2025-09-17T18:45:08.114+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1834) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-17T18:45:08.115+0000] {standard_task_runner.py:72} INFO - Started process 1835 to run task
[2025-09-17T18:45:08.185+0000] {task_command.py:467} INFO - Running <TaskInstance: rakuten_multimodal_pipeline.check_training_data manual__2025-09-17T18:45:06.127533+00:00 [running]> on host 7366b2a8eb62
[2025-09-17T18:45:08.608+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='rakuten_multimodal_pipeline' AIRFLOW_CTX_TASK_ID='check_training_data' AIRFLOW_CTX_EXECUTION_DATE='2025-09-17T18:45:06.127533+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-17T18:45:06.127533+00:00'
[2025-09-17T18:45:08.612+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-09-17T18:45:08.709+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-17T18:45:08.713+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "echo '=== Checking data availability ===' && ls -lh /opt/airflow/data/ && [ -d /opt/airflow/data/images/image_train ] || (echo 'Missing image_train dir' && exit 1) && [ -d /opt/airflow/data/images/image_sample ] || (echo 'Missing image_sample dir' && exit 1) && echo 'âœ“ All expected data present'"]
[2025-09-17T18:45:08.728+0000] {subprocess.py:86} INFO - Output:
[2025-09-17T18:45:08.737+0000] {subprocess.py:93} INFO - === Checking data availability ===
[2025-09-17T18:45:08.743+0000] {subprocess.py:93} INFO - total 0
[2025-09-17T18:45:08.746+0000] {subprocess.py:93} INFO - Missing image_train dir
[2025-09-17T18:45:08.747+0000] {subprocess.py:93} INFO - Missing image_sample dir
[2025-09-17T18:45:08.748+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-09-17T18:45:08.765+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-09-17T18:45:08.830+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=rakuten_multimodal_pipeline, task_id=check_training_data, run_id=manual__2025-09-17T18:45:06.127533+00:00, execution_date=20250917T184506, start_date=20250917T184508, end_date=20250917T184508
[2025-09-17T18:45:08.872+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-09-17T18:45:08.873+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 6 for task check_training_data (Bash command failed. The command returned a non-zero exit code 1.; 1835)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-09-17T18:45:08.910+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-09-17T18:45:08.951+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-17T18:45:08.954+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
