[2025-09-08T18:36:42.643+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-08T18:36:42.696+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: train_model_dag_batch_iterative_85000.train_model_iterative manual__2025-09-08T18:35:47.983843+00:00 [queued]>
[2025-09-08T18:36:42.727+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: train_model_dag_batch_iterative_85000.train_model_iterative manual__2025-09-08T18:35:47.983843+00:00 [queued]>
[2025-09-08T18:36:42.729+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-09-08T18:36:42.777+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): train_model_iterative> on 2025-09-08 18:35:47.983843+00:00
[2025-09-08T18:36:42.794+0000] {standard_task_runner.py:63} INFO - Started process 5679 to run task
[2025-09-08T18:36:42.802+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'train_model_dag_batch_iterative_85000', 'train_model_iterative', 'manual__2025-09-08T18:35:47.983843+00:00', '--job-id', '394', '--raw', '--subdir', 'DAGS_FOLDER/train_dag.py', '--cfg-path', '/tmp/tmp2t1k_uvw']
[2025-09-08T18:36:42.809+0000] {standard_task_runner.py:91} INFO - Job 394: Subtask train_model_iterative
[2025-09-08T18:36:42.930+0000] {task_command.py:426} INFO - Running <TaskInstance: train_model_dag_batch_iterative_85000.train_model_iterative manual__2025-09-08T18:35:47.983843+00:00 [running]> on host 50a52b70bec0
[2025-09-08T18:36:43.164+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='train_model_dag_batch_iterative_85000' AIRFLOW_CTX_TASK_ID='train_model_iterative' AIRFLOW_CTX_EXECUTION_DATE='2025-09-08T18:35:47.983843+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-08T18:35:47.983843+00:00'
[2025-09-08T18:36:43.166+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-08T18:41:23.558+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-08T18:41:23.584+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/train_dag.py", line 99, in send_batches_to_train_api
    raise Exception(f"Batch {idx} failed: {response.text}")
Exception: Batch 1 failed: Internal Server Error
[2025-09-08T18:41:23.708+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=train_model_dag_batch_iterative_85000, task_id=train_model_iterative, run_id=manual__2025-09-08T18:35:47.983843+00:00, execution_date=20250908T183547, start_date=20250908T183642, end_date=20250908T184123
[2025-09-08T18:41:23.810+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 394 for task train_model_iterative (Batch 1 failed: Internal Server Error; 5679)
[2025-09-08T18:41:23.895+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-09-08T18:41:24.003+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-08T18:41:24.007+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
